//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildVision.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildVision.UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string BuildActionBuild {
            get {
                return ResourceManager.GetString("BuildActionBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started at.
        /// </summary>
        public static string BuildActionBuild_BeginAtString {
            get {
                return ResourceManager.GetString("BuildActionBuild_BeginAtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canceled.
        /// </summary>
        public static string BuildActionCancelled {
            get {
                return ResourceManager.GetString("BuildActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canceled.
        /// </summary>
        public static string BuildActionCancelled_Clean {
            get {
                return ResourceManager.GetString("BuildActionCancelled_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string BuildActionClean {
            get {
                return ResourceManager.GetString("BuildActionClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started at.
        /// </summary>
        public static string BuildActionClean_BeginAtString {
            get {
                return ResourceManager.GetString("BuildActionClean_BeginAtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string BuildActionFailed {
            get {
                return ResourceManager.GetString("BuildActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string BuildActionFailed_Clean {
            get {
                return ResourceManager.GetString("BuildActionFailed_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        public static string BuildActionFinished {
            get {
                return ResourceManager.GetString("BuildActionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        public static string BuildActionFinished_Clean {
            get {
                return ResourceManager.GetString("BuildActionFinished_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed successfully.
        /// </summary>
        public static string BuildActionFinishedSuccessfully {
            get {
                return ResourceManager.GetString("BuildActionFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed successfully.
        /// </summary>
        public static string BuildActionFinishedSuccessfully_Clean {
            get {
                return ResourceManager.GetString("BuildActionFinishedSuccessfully_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string BuildActionRebuildAll {
            get {
                return ResourceManager.GetString("BuildActionRebuildAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started at.
        /// </summary>
        public static string BuildActionRebuildAll_BeginAtString {
            get {
                return ResourceManager.GetString("BuildActionRebuildAll_BeginAtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} {3}.
        /// </summary>
        public static string BuildBeginStateLabelTemplate_Default {
            get {
                return ResourceManager.GetString("BuildBeginStateLabelTemplate_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        public static string BuildBeginStateLabelTemplate_ShortForm {
            get {
                return ResourceManager.GetString("BuildBeginStateLabelTemplate_ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} at {3}.
        /// </summary>
        public static string BuildDoneStateLabelTemplate_Default {
            get {
                return ResourceManager.GetString("BuildDoneStateLabelTemplate_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} at {2}.
        /// </summary>
        public static string BuildDoneStateLabelTemplate_ShortForm {
            get {
                return ResourceManager.GetString("BuildDoneStateLabelTemplate_ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVision.
        /// </summary>
        public static string BuildDoneText_BuildNotStarted {
            get {
                return ResourceManager.GetString("BuildDoneText_BuildNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed at {0}.
        /// </summary>
        public static string BuildDoneText_NotSupported_BuildActionOrScopeIsNull_CompletedAtTemplate {
            get {
                return ResourceManager.GetString("BuildDoneText_NotSupported_BuildActionOrScopeIsNull_CompletedAtTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of elapsed time.
        /// </summary>
        public static string BuildMessagesSettings_AgoTimeHeader {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_AgoTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String format
        ///on build begin.
        /// </summary>
        public static string BuildMessagesSettings_BuildBeginStringFormatLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_BuildBeginStringFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String format
        ///on build done.
        /// </summary>
        public static string BuildMessagesSettings_BuildDoneStringFormatLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_BuildDoneStringFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format.
        /// </summary>
        public static string BuildMessagesSettings_DateTimeFormatLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DateTimeFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time template.
        /// </summary>
        public static string BuildMessagesSettings_DateTimeTemplateLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DateTimeTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay, sec.
        /// </summary>
        public static string BuildMessagesSettings_DelayLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display:.
        /// </summary>
        public static string BuildMessagesSettings_DisplayLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warning icon for builds.
        /// </summary>
        public static string BuildMessagesSettings_DisplayWarningSignCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DisplayWarningSignCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide UpToDate targets.
        /// </summary>
        public static string BuildMessagesSettings_HideUpToDateTargets {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_HideUpToDateTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        public static string BuildMessagesSettings_ShowAgoTimeCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_ShowAgoTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name (in the case of a building project).
        /// </summary>
        public static string BuildMessagesSettings_ShowProjectNameCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_ShowProjectNameCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution name (in the case of a building solution).
        /// </summary>
        public static string BuildMessagesSettings_ShowSolutionNameCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_ShowSolutionNameCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display messages in VisualStudio Status Bar.
        /// </summary>
        public static string BuildMessagesSettings_StatusBarOutputCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_StatusBarOutputCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String format.
        /// </summary>
        public static string BuildMessagesSettings_StringFormatLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_StringFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String template.
        /// </summary>
        public static string BuildMessagesSettings_StringTemplateLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_StringTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        public static string BuildScopeBatch_UnitName {
            get {
                return ResourceManager.GetString("BuildScopeBatch_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &apos;{0}&apos;.
        /// </summary>
        public static string BuildScopeProject_ProjectNameTemplate {
            get {
                return ResourceManager.GetString("BuildScopeProject_ProjectNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the project.
        /// </summary>
        public static string BuildScopeProject_UnitName {
            get {
                return ResourceManager.GetString("BuildScopeProject_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &apos;{0}&apos;.
        /// </summary>
        public static string BuildScopeSolution_SolutionNameTemplate {
            get {
                return ResourceManager.GetString("BuildScopeSolution_SolutionNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solution.
        /// </summary>
        public static string BuildScopeSolution_UnitName {
            get {
                return ResourceManager.GetString("BuildScopeSolution_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build solution.
        /// </summary>
        public static string BuildSolutionButtonTooltip {
            get {
                return ResourceManager.GetString("BuildSolutionButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBuildSolutionButtonCaption {
            get {
                return ResourceManager.GetString("CancelBuildSolutionButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel build.
        /// </summary>
        public static string CancelBuildSolutionButtonTooltip {
            get {
                return ResourceManager.GetString("CancelBuildSolutionButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        public static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean solution.
        /// </summary>
        public static string CleanSolutionButtonTooltip {
            get {
                return ResourceManager.GetString("CleanSolutionButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own time format.
        /// </summary>
        public static string EnumBuildStateExtraLabelTemplate_Advanced {
            get {
                return ResourceManager.GetString("EnumBuildStateExtraLabelTemplate_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalMinutes.
        /// </summary>
        public static string EnumBuildStateExtraLabelTemplate_TotalMinutes {
            get {
                return ResourceManager.GetString("EnumBuildStateExtraLabelTemplate_TotalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalMinutes:Seconds.
        /// </summary>
        public static string EnumBuildStateExtraLabelTemplate_TotalMinutesWithSeconds {
            get {
                return ResourceManager.GetString("EnumBuildStateExtraLabelTemplate_TotalMinutesWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSeconds.
        /// </summary>
        public static string EnumBuildStateExtraLabelTemplate_TotalSeconds {
            get {
                return ResourceManager.GetString("EnumBuildStateExtraLabelTemplate_TotalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string EnumBuildStateLabelTemplate_Default {
            get {
                return ResourceManager.GetString("EnumBuildStateLabelTemplate_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short form.
        /// </summary>
        public static string EnumBuildStateLabelTemplate_ShortForm {
            get {
                return ResourceManager.GetString("EnumBuildStateLabelTemplate_ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▲.
        /// </summary>
        public static string EnumSortOrder_Asc {
            get {
                return ResourceManager.GetString("EnumSortOrder_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▼.
        /// </summary>
        public static string EnumSortOrder_Desc {
            get {
                return ResourceManager.GetString("EnumSortOrder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        public static string EnumSortOrder_None {
            get {
                return ResourceManager.GetString("EnumSortOrder_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        public static string EnumWindowState_Close {
            get {
                return ResourceManager.GetString("EnumWindowState_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize window*.
        /// </summary>
        public static string EnumWindowState_Hide {
            get {
                return ResourceManager.GetString("EnumWindowState_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Minimization is supported only for the docked window. The floating window or window attached like document will be closed..
        /// </summary>
        public static string EnumWindowState_Hide_Footnote {
            get {
                return ResourceManager.GetString("EnumWindowState_Hide_Footnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t change window state.
        /// </summary>
        public static string EnumWindowState_Nothing {
            get {
                return ResourceManager.GetString("EnumWindowState_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window.
        /// </summary>
        public static string EnumWindowState_Show {
            get {
                return ResourceManager.GetString("EnumWindowState_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window (don&apos;t activate).
        /// </summary>
        public static string EnumWindowState_ShowNoActivate {
            get {
                return ResourceManager.GetString("EnumWindowState_ShowNoActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of failed projects.
        /// </summary>
        public static string ErrorProjectsIndicator_Description {
            get {
                return ResourceManager.GetString("ErrorProjectsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed projects.
        /// </summary>
        public static string ErrorProjectsIndicator_Header {
            get {
                return ResourceManager.GetString("ErrorProjectsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of MSBuild errors.
        /// </summary>
        public static string ErrorsIndicator_Description {
            get {
                return ResourceManager.GetString("ErrorsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string ErrorsIndicator_Header {
            get {
                return ResourceManager.GetString("ErrorsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available since Windows 7.
        /// </summary>
        public static string GeneralSettings_DisplayTaskBarProgressAvailableWin7Tooltip {
            get {
                return ResourceManager.GetString("GeneralSettings_DisplayTaskBarProgressAvailableWin7Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display build progress on Windows Taskbar.
        /// </summary>
        public static string GeneralSettings_DisplayTaskBarProgressCheckBox {
            get {
                return ResourceManager.GetString("GeneralSettings_DisplayTaskBarProgressCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill projects list on build begin.
        /// </summary>
        public static string GeneralSettings_FillProjectListOnBuildBeginCheckBox {
            get {
                return ResourceManager.GetString("GeneralSettings_FillProjectListOnBuildBeginCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show indicators panel.
        /// </summary>
        public static string GeneralSettings_IndicatorsPanelVisibleCheckBox {
            get {
                return ResourceManager.GetString("GeneralSettings_IndicatorsPanelVisibleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to build failure reason.
        /// </summary>
        public static string GeneralSettings_NavigateToBuildFailureReasonLabel {
            get {
                return ResourceManager.GetString("GeneralSettings_NavigateToBuildFailureReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the first MSBuild error.
        /// </summary>
        public static string GeneralSettings_NavigateToBuildFailureReasonLabelToolTip {
            get {
                return ResourceManager.GetString("GeneralSettings_NavigateToBuildFailureReasonLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset progress after build done.
        /// </summary>
        public static string GeneralSettings_ResetTaskBarProgressAfterBuildDoneLabel {
            get {
                return ResourceManager.GetString("GeneralSettings_ResetTaskBarProgressAfterBuildDoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop building on the first error.
        /// </summary>
        public static string GeneralSettings_StopBuildAfterFirstErrorCheckBox {
            get {
                return ResourceManager.GetString("GeneralSettings_StopBuildAfterFirstErrorCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the Build or Rebuild immediately, if an MSBuild error occurs or one project fails to build.
        /// </summary>
        public static string GeneralSettings_StopBuildAfterFirstErrorCheckBoxToolTip {
            get {
                return ResourceManager.GetString("GeneralSettings_StopBuildAfterFirstErrorCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N\A.
        /// </summary>
        public static string GridCellNAText {
            get {
                return ResourceManager.GetString("GridCellNAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;N\A&gt;.
        /// </summary>
        public static string GridCellNATextInBrackets {
            get {
                return ResourceManager.GetString("GridCellNATextInBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string GridCellNoneText {
            get {
                return ResourceManager.GetString("GridCellNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        public static string GridCellNoneTextInBrackets {
            get {
                return ResourceManager.GetString("GridCellNoneTextInBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Group.
        /// </summary>
        public static string GridColumnsGroupMenuItems {
            get {
                return ResourceManager.GetString("GridColumnsGroupMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string GridColumnsMenuItems {
            get {
                return ResourceManager.GetString("GridColumnsMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Customize....
        /// </summary>
        public static string GridColumnsOpenSettingsMenuItem {
            get {
                return ResourceManager.GetString("GridColumnsOpenSettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColExample {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColFormat {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColHeader {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColName {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColWidth {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show Header.
        /// </summary>
        public static string GridHeaderVisibleMenuItem {
            get {
                return ResourceManager.GetString("GridHeaderVisibleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group header format.
        /// </summary>
        public static string GridSettings_GroupHeaderFormat {
            get {
                return ResourceManager.GetString("GridSettings_GroupHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format arguments.
        /// </summary>
        public static string GridSettings_GroupHeaderFormat_MenuArgsToolTip {
            get {
                return ResourceManager.GetString("GridSettings_GroupHeaderFormat_MenuArgsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string GridSettings_Grouping {
            get {
                return ResourceManager.GetString("GridSettings_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show header.
        /// </summary>
        public static string GridSettings_ShowHeader {
            get {
                return ResourceManager.GetString("GridSettings_ShowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string GridSettings_Sorting {
            get {
                return ResourceManager.GetString("GridSettings_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format tip: you can use .NET format strings and {0} argument..
        /// </summary>
        public static string GridSettingsControl_ColumnsTip {
            get {
                return ResourceManager.GetString("GridSettingsControl_ColumnsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide UpToDate targets.
        /// </summary>
        public static string HideUpToDateTargetsMenuItem {
            get {
                return ResourceManager.GetString("HideUpToDateTargetsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Invalid format&gt;.
        /// </summary>
        public static string InvalidTimeStringFormat {
            get {
                return ResourceManager.GetString("InvalidTimeStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of MSBuild messages.
        /// </summary>
        public static string MessagesIndicator_Description {
            get {
                return ResourceManager.GetString("MessagesIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesIndicator_Header {
            get {
                return ResourceManager.GetString("MessagesIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string NavigateToBuildFailureReasonCondition_Disabled {
            get {
                return ResourceManager.GetString("NavigateToBuildFailureReasonCondition_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Build Failed.
        /// </summary>
        public static string NavigateToBuildFailureReasonCondition_OnBuildDone {
            get {
                return ResourceManager.GetString("NavigateToBuildFailureReasonCondition_OnBuildDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Error Raised.
        /// </summary>
        public static string NavigateToBuildFailureReasonCondition_OnErrorRaised {
            get {
                return ResourceManager.GetString("NavigateToBuildFailureReasonCondition_OnErrorRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string NoneMenuItem {
            get {
                return ResourceManager.GetString("NoneMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Settings....
        /// </summary>
        public static string OpenGeneralSettingsMenuItem {
            get {
                return ResourceManager.GetString("OpenGeneralSettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVision.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        public static string ProjectItemHeader_BuildElapsedTime {
            get {
                return ResourceManager.GetString("ProjectItemHeader_BuildElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build finish time .
        /// </summary>
        public static string ProjectItemHeader_BuildFinishTime {
            get {
                return ResourceManager.GetString("ProjectItemHeader_BuildFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildOrder.
        /// </summary>
        public static string ProjectItemHeader_BuildOrder {
            get {
                return ResourceManager.GetString("ProjectItemHeader_BuildOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build start time.
        /// </summary>
        public static string ProjectItemHeader_BuildStartTime {
            get {
                return ResourceManager.GetString("ProjectItemHeader_BuildStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonType.
        /// </summary>
        public static string ProjectItemHeader_CommonType {
            get {
                return ResourceManager.GetString("ProjectItemHeader_CommonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ProjectItemHeader_Configuration {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string ProjectItemHeader_ErrorsCount {
            get {
                return ResourceManager.GetString("ProjectItemHeader_ErrorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extenders.
        /// </summary>
        public static string ProjectItemHeader_ExtenderNames {
            get {
                return ResourceManager.GetString("ProjectItemHeader_ExtenderNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ProjectItemHeader_FlavourType {
            get {
                return ResourceManager.GetString("ProjectItemHeader_FlavourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        public static string ProjectItemHeader_Framework {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string ProjectItemHeader_FullName {
            get {
                return ResourceManager.GetString("ProjectItemHeader_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullPath.
        /// </summary>
        public static string ProjectItemHeader_FullPath {
            get {
                return ResourceManager.GetString("ProjectItemHeader_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ProjectItemHeader_Language {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainType.
        /// </summary>
        public static string ProjectItemHeader_MainFlavourType {
            get {
                return ResourceManager.GetString("ProjectItemHeader_MainFlavourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string ProjectItemHeader_MessagesCount {
            get {
                return ResourceManager.GetString("ProjectItemHeader_MessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProjectItemHeader_Name {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string ProjectItemHeader_OutputType {
            get {
                return ResourceManager.GetString("ProjectItemHeader_OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string ProjectItemHeader_Platform {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string ProjectItemHeader_RootNamespace {
            get {
                return ResourceManager.GetString("ProjectItemHeader_RootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolutionFolder.
        /// </summary>
        public static string ProjectItemHeader_SolutionFolder {
            get {
                return ResourceManager.GetString("ProjectItemHeader_SolutionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ProjectItemHeader_State {
            get {
                return ResourceManager.GetString("ProjectItemHeader_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StateIcon.
        /// </summary>
        public static string ProjectItemHeader_StateBitmap {
            get {
                return ResourceManager.GetString("ProjectItemHeader_StateBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniqueName.
        /// </summary>
        public static string ProjectItemHeader_UniqueName {
            get {
                return ResourceManager.GetString("ProjectItemHeader_UniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string ProjectItemHeader_WarningsCount {
            get {
                return ResourceManager.GetString("ProjectItemHeader_WarningsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item &quot;Build Output Files&quot;.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_ExpanderHeader {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_ExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built assemblies.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_BuiltAssemblies {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_BuiltAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content files.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_ContentFiles {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_ContentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_Documentation {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized resources.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_LocalizedRes {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_LocalizedRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_Symbols {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML-serialization assemblies.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_XmlSerAssemblies {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_XmlSerAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to the Clipboard.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_TypesLabel {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_TypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild solution.
        /// </summary>
        public static string RebuildSolutionButtonTooltip {
            get {
                return ResourceManager.GetString("RebuildSolutionButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issues ....
        /// </summary>
        public static string ReportIssues {
            get {
                return ResourceManager.GetString("ReportIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset after delay.
        /// </summary>
        public static string ResetTaskBarItemInfoCondition_AfterDelay {
            get {
                return ResourceManager.GetString("ResetTaskBarItemInfoCondition_AfterDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset after mouse click.
        /// </summary>
        public static string ResetTaskBarItemInfoCondition_ByMouseClick {
            get {
                return ResourceManager.GetString("ResetTaskBarItemInfoCondition_ByMouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetTaskBarItemInfoCondition_Immediately {
            get {
                return ResourceManager.GetString("ResetTaskBarItemInfoCondition_Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not reset.
        /// </summary>
        public static string ResetTaskBarItemInfoCondition_Never {
            get {
                return ResourceManager.GetString("ResetTaskBarItemInfoCondition_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to the Clipboard.
        /// </summary>
        public static string SelectedProjectItem_CopyBuildOutputFilesToClipboard_CopyMenuItem {
            get {
                return ResourceManager.GetString("SelectedProjectItem_CopyBuildOutputFilesToClipboard_CopyMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Output Files.
        /// </summary>
        public static string SelectedProjectItem_CopyBuildOutputFilesToClipboard_ParentMenuItem {
            get {
                return ResourceManager.GetString("SelectedProjectItem_CopyBuildOutputFilesToClipboard_ParentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Containing Folder.
        /// </summary>
        public static string SelectedProjectItem_OpenContainingFolder_MenuItem {
            get {
                return ResourceManager.GetString("SelectedProjectItem_OpenContainingFolder_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Selected Project.
        /// </summary>
        public static string SelectedProjectItemMenuItems {
            get {
                return ResourceManager.GetString("SelectedProjectItemMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Separator).
        /// </summary>
        public static string SeparatorIndicator_Header {
            get {
                return ResourceManager.GetString("SeparatorIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of succeeded projects.
        /// </summary>
        public static string SuccessProjectsIndicator_Description {
            get {
                return ResourceManager.GetString("SuccessProjectsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded projects.
        /// </summary>
        public static string SuccessProjectsIndicator_Header {
            get {
                return ResourceManager.GetString("SuccessProjectsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildVision.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is executed. Please wait....
        /// </summary>
        public static string UnknownBuildActionOrScope_BuildBeginText {
            get {
                return ResourceManager.GetString("UnknownBuildActionOrScope_BuildBeginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception.
        /// </summary>
        public static string UnknownExceptionMsg {
            get {
                return ResourceManager.GetString("UnknownExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of projects which are up-to-date.
        /// </summary>
        public static string UpToDateProjectsIndicator_Description {
            get {
                return ResourceManager.GetString("UpToDateProjectsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-to-date Projects.
        /// </summary>
        public static string UpToDateProjectsIndicator_Header {
            get {
                return ResourceManager.GetString("UpToDateProjectsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of projects with warnings.
        /// </summary>
        public static string WarningProjectsIndicator_Description {
            get {
                return ResourceManager.GetString("WarningProjectsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects with warnings.
        /// </summary>
        public static string WarningProjectsIndicator_Header {
            get {
                return ResourceManager.GetString("WarningProjectsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of MSBuild warnings.
        /// </summary>
        public static string WarningsIndicator_Description {
            get {
                return ResourceManager.GetString("WarningsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string WarningsIndicator_Header {
            get {
                return ResourceManager.GetString("WarningsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay, ms.
        /// </summary>
        public static string WindowSettings_DelayLabel {
            get {
                return ResourceManager.GetString("WindowSettings_DelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State on build begin.
        /// </summary>
        public static string WindowSettings_WindowActionOnBuildBegin {
            get {
                return ResourceManager.GetString("WindowSettings_WindowActionOnBuildBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State on build error.
        /// </summary>
        public static string WindowSettings_WindowActionOnBuildError {
            get {
                return ResourceManager.GetString("WindowSettings_WindowActionOnBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State on build success.
        /// </summary>
        public static string WindowSettings_WindowActionOnBuildSuccess {
            get {
                return ResourceManager.GetString("WindowSettings_WindowActionOnBuildSuccess", resourceCulture);
            }
        }
    }
}
