//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildVision.UI {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildVision.UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build ähnelt.
        /// </summary>
        public static string BuildActionBuild {
            get {
                return ResourceManager.GetString("BuildActionBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die started at ähnelt.
        /// </summary>
        public static string BuildActionBuild_BeginAtString {
            get {
                return ResourceManager.GetString("BuildActionBuild_BeginAtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die canceled ähnelt.
        /// </summary>
        public static string BuildActionCancelled {
            get {
                return ResourceManager.GetString("BuildActionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die canceled ähnelt.
        /// </summary>
        public static string BuildActionCancelled_Clean {
            get {
                return ResourceManager.GetString("BuildActionCancelled_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clean ähnelt.
        /// </summary>
        public static string BuildActionClean {
            get {
                return ResourceManager.GetString("BuildActionClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die started at ähnelt.
        /// </summary>
        public static string BuildActionClean_BeginAtString {
            get {
                return ResourceManager.GetString("BuildActionClean_BeginAtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die failed ähnelt.
        /// </summary>
        public static string BuildActionFailed {
            get {
                return ResourceManager.GetString("BuildActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die failed ähnelt.
        /// </summary>
        public static string BuildActionFailed_Clean {
            get {
                return ResourceManager.GetString("BuildActionFailed_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die completed ähnelt.
        /// </summary>
        public static string BuildActionFinished {
            get {
                return ResourceManager.GetString("BuildActionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die completed ähnelt.
        /// </summary>
        public static string BuildActionFinished_Clean {
            get {
                return ResourceManager.GetString("BuildActionFinished_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die completed successfully ähnelt.
        /// </summary>
        public static string BuildActionFinishedSuccessfully {
            get {
                return ResourceManager.GetString("BuildActionFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die completed successfully ähnelt.
        /// </summary>
        public static string BuildActionFinishedSuccessfully_Clean {
            get {
                return ResourceManager.GetString("BuildActionFinishedSuccessfully_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rebuild ähnelt.
        /// </summary>
        public static string BuildActionRebuildAll {
            get {
                return ResourceManager.GetString("BuildActionRebuildAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die started at ähnelt.
        /// </summary>
        public static string BuildActionRebuildAll_BeginAtString {
            get {
                return ResourceManager.GetString("BuildActionRebuildAll_BeginAtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} {2} {3} ähnelt.
        /// </summary>
        public static string BuildBeginStateLabelTemplate_Default {
            get {
                return ResourceManager.GetString("BuildBeginStateLabelTemplate_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} {2} ähnelt.
        /// </summary>
        public static string BuildBeginStateLabelTemplate_ShortForm {
            get {
                return ResourceManager.GetString("BuildBeginStateLabelTemplate_ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} {2} at {3} ähnelt.
        /// </summary>
        public static string BuildDoneStateLabelTemplate_Default {
            get {
                return ResourceManager.GetString("BuildDoneStateLabelTemplate_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} at {2} ähnelt.
        /// </summary>
        public static string BuildDoneStateLabelTemplate_ShortForm {
            get {
                return ResourceManager.GetString("BuildDoneStateLabelTemplate_ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BuildVision ähnelt.
        /// </summary>
        public static string BuildDoneText_BuildNotStarted {
            get {
                return ResourceManager.GetString("BuildDoneText_BuildNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Completed at {0} ähnelt.
        /// </summary>
        public static string BuildDoneText_NotSupported_BuildActionOrScopeIsNull_CompletedAtTemplate {
            get {
                return ResourceManager.GetString("BuildDoneText_NotSupported_BuildActionOrScopeIsNull_CompletedAtTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line of elapsed time ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_AgoTimeHeader {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_AgoTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String format
        ///on build begin ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_BuildBeginStringFormatLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_BuildBeginStringFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String format
        ///on build done ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_BuildDoneStringFormatLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_BuildDoneStringFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time format ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_DateTimeFormatLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DateTimeFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time template ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_DateTimeTemplateLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DateTimeTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delay, sec ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_DelayLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display: ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_DisplayLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DisplayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show warning icon for builds ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_DisplayWarningSignCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_DisplayWarningSignCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide UpToDate targets ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_HideUpToDateTargets {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_HideUpToDateTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elapsed time ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_ShowAgoTimeCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_ShowAgoTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project name (in the case of a building project) ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_ShowProjectNameCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_ShowProjectNameCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solution name (in the case of a building solution) ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_ShowSolutionNameCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_ShowSolutionNameCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display messages in VisualStudio Status Bar ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_StatusBarOutputCheckBox {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_StatusBarOutputCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String format ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_StringFormatLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_StringFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String template ähnelt.
        /// </summary>
        public static string BuildMessagesSettings_StringTemplateLabel {
            get {
                return ResourceManager.GetString("BuildMessagesSettings_StringTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die projects ähnelt.
        /// </summary>
        public static string BuildScopeBatch_UnitName {
            get {
                return ResourceManager.GetString("BuildScopeBatch_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  &apos;{0}&apos; ähnelt.
        /// </summary>
        public static string BuildScopeProject_ProjectNameTemplate {
            get {
                return ResourceManager.GetString("BuildScopeProject_ProjectNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the project ähnelt.
        /// </summary>
        public static string BuildScopeProject_UnitName {
            get {
                return ResourceManager.GetString("BuildScopeProject_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  &apos;{0}&apos; ähnelt.
        /// </summary>
        public static string BuildScopeSolution_SolutionNameTemplate {
            get {
                return ResourceManager.GetString("BuildScopeSolution_SolutionNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die solution ähnelt.
        /// </summary>
        public static string BuildScopeSolution_UnitName {
            get {
                return ResourceManager.GetString("BuildScopeSolution_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build solution ähnelt.
        /// </summary>
        public static string BuildSolutionButtonTooltip {
            get {
                return ResourceManager.GetString("BuildSolutionButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string CancelBuildSolutionButtonCaption {
            get {
                return ResourceManager.GetString("CancelBuildSolutionButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel build ähnelt.
        /// </summary>
        public static string CancelBuildSolutionButtonTooltip {
            get {
                return ResourceManager.GetString("CancelBuildSolutionButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not create tool window. ähnelt.
        /// </summary>
        public static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clean solution ähnelt.
        /// </summary>
        public static string CleanSolutionButtonTooltip {
            get {
                return ResourceManager.GetString("CleanSolutionButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Own time format ähnelt.
        /// </summary>
        public static string EnumBuildStateExtraLabelTemplate_Advanced {
            get {
                return ResourceManager.GetString("EnumBuildStateExtraLabelTemplate_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TotalMinutes ähnelt.
        /// </summary>
        public static string EnumBuildStateExtraLabelTemplate_TotalMinutes {
            get {
                return ResourceManager.GetString("EnumBuildStateExtraLabelTemplate_TotalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TotalMinutes:Seconds ähnelt.
        /// </summary>
        public static string EnumBuildStateExtraLabelTemplate_TotalMinutesWithSeconds {
            get {
                return ResourceManager.GetString("EnumBuildStateExtraLabelTemplate_TotalMinutesWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TotalSeconds ähnelt.
        /// </summary>
        public static string EnumBuildStateExtraLabelTemplate_TotalSeconds {
            get {
                return ResourceManager.GetString("EnumBuildStateExtraLabelTemplate_TotalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string EnumBuildStateLabelTemplate_Default {
            get {
                return ResourceManager.GetString("EnumBuildStateLabelTemplate_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short form ähnelt.
        /// </summary>
        public static string EnumBuildStateLabelTemplate_ShortForm {
            get {
                return ResourceManager.GetString("EnumBuildStateLabelTemplate_ShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ▲ ähnelt.
        /// </summary>
        public static string EnumSortOrder_Asc {
            get {
                return ResourceManager.GetString("EnumSortOrder_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ▼ ähnelt.
        /// </summary>
        public static string EnumSortOrder_Desc {
            get {
                return ResourceManager.GetString("EnumSortOrder_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die     ähnelt.
        /// </summary>
        public static string EnumSortOrder_None {
            get {
                return ResourceManager.GetString("EnumSortOrder_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close window ähnelt.
        /// </summary>
        public static string EnumWindowState_Close {
            get {
                return ResourceManager.GetString("EnumWindowState_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize window* ähnelt.
        /// </summary>
        public static string EnumWindowState_Hide {
            get {
                return ResourceManager.GetString("EnumWindowState_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die * Minimization is supported only for the docked window. The floating window or window attached like document will be closed. ähnelt.
        /// </summary>
        public static string EnumWindowState_Hide_Footnote {
            get {
                return ResourceManager.GetString("EnumWindowState_Hide_Footnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t change window state ähnelt.
        /// </summary>
        public static string EnumWindowState_Nothing {
            get {
                return ResourceManager.GetString("EnumWindowState_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show window ähnelt.
        /// </summary>
        public static string EnumWindowState_Show {
            get {
                return ResourceManager.GetString("EnumWindowState_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show window (don&apos;t activate) ähnelt.
        /// </summary>
        public static string EnumWindowState_ShowNoActivate {
            get {
                return ResourceManager.GetString("EnumWindowState_ShowNoActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of failed projects ähnelt.
        /// </summary>
        public static string ErrorProjectsIndicator_Description {
            get {
                return ResourceManager.GetString("ErrorProjectsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed projects ähnelt.
        /// </summary>
        public static string ErrorProjectsIndicator_Header {
            get {
                return ResourceManager.GetString("ErrorProjectsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of MSBuild errors ähnelt.
        /// </summary>
        public static string ErrorsIndicator_Description {
            get {
                return ResourceManager.GetString("ErrorsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Errors ähnelt.
        /// </summary>
        public static string ErrorsIndicator_Header {
            get {
                return ResourceManager.GetString("ErrorsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available since Windows 7 ähnelt.
        /// </summary>
        public static string GeneralSettings_DisplayTaskBarProgressAvailableWin7Tooltip {
            get {
                return ResourceManager.GetString("GeneralSettings_DisplayTaskBarProgressAvailableWin7Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display build progress on Windows Taskbar ähnelt.
        /// </summary>
        public static string GeneralSettings_DisplayTaskBarProgressCheckBox {
            get {
                return ResourceManager.GetString("GeneralSettings_DisplayTaskBarProgressCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fill projects list on build begin ähnelt.
        /// </summary>
        public static string GeneralSettings_FillProjectListOnBuildBeginCheckBox {
            get {
                return ResourceManager.GetString("GeneralSettings_FillProjectListOnBuildBeginCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show indicators panel ähnelt.
        /// </summary>
        public static string GeneralSettings_IndicatorsPanelVisibleCheckBox {
            get {
                return ResourceManager.GetString("GeneralSettings_IndicatorsPanelVisibleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigate to build failure reason ähnelt.
        /// </summary>
        public static string GeneralSettings_NavigateToBuildFailureReasonLabel {
            get {
                return ResourceManager.GetString("GeneralSettings_NavigateToBuildFailureReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigate to the first MSBuild error ähnelt.
        /// </summary>
        public static string GeneralSettings_NavigateToBuildFailureReasonLabelToolTip {
            get {
                return ResourceManager.GetString("GeneralSettings_NavigateToBuildFailureReasonLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset progress after build done ähnelt.
        /// </summary>
        public static string GeneralSettings_ResetTaskBarProgressAfterBuildDoneLabel {
            get {
                return ResourceManager.GetString("GeneralSettings_ResetTaskBarProgressAfterBuildDoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop building on the first error ähnelt.
        /// </summary>
        public static string GeneralSettings_StopBuildAfterFirstErrorCheckBox {
            get {
                return ResourceManager.GetString("GeneralSettings_StopBuildAfterFirstErrorCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stops the Build or Rebuild immediately, if an MSBuild error occurs or one project fails to build ähnelt.
        /// </summary>
        public static string GeneralSettings_StopBuildAfterFirstErrorCheckBoxToolTip {
            get {
                return ResourceManager.GetString("GeneralSettings_StopBuildAfterFirstErrorCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N\A ähnelt.
        /// </summary>
        public static string GridCellNAText {
            get {
                return ResourceManager.GetString("GridCellNAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;N\A&gt; ähnelt.
        /// </summary>
        public static string GridCellNATextInBrackets {
            get {
                return ResourceManager.GetString("GridCellNATextInBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string GridCellNoneText {
            get {
                return ResourceManager.GetString("GridCellNoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;none&gt; ähnelt.
        /// </summary>
        public static string GridCellNoneTextInBrackets {
            get {
                return ResourceManager.GetString("GridCellNoneTextInBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Group ähnelt.
        /// </summary>
        public static string GridColumnsGroupMenuItems {
            get {
                return ResourceManager.GetString("GridColumnsGroupMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Columns ähnelt.
        /// </summary>
        public static string GridColumnsMenuItems {
            get {
                return ResourceManager.GetString("GridColumnsMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Customize... ähnelt.
        /// </summary>
        public static string GridColumnsOpenSettingsMenuItem {
            get {
                return ResourceManager.GetString("GridColumnsOpenSettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Example ähnelt.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColExample {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format ähnelt.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColFormat {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Header ähnelt.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColHeader {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColName {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        /// </summary>
        public static string GridColumnsSettingsWindow_ColWidth {
            get {
                return ResourceManager.GetString("GridColumnsSettingsWindow_ColWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Show Header ähnelt.
        /// </summary>
        public static string GridHeaderVisibleMenuItem {
            get {
                return ResourceManager.GetString("GridHeaderVisibleMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group header format ähnelt.
        /// </summary>
        public static string GridSettings_GroupHeaderFormat {
            get {
                return ResourceManager.GetString("GridSettings_GroupHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format arguments ähnelt.
        /// </summary>
        public static string GridSettings_GroupHeaderFormat_MenuArgsToolTip {
            get {
                return ResourceManager.GetString("GridSettings_GroupHeaderFormat_MenuArgsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grouping ähnelt.
        /// </summary>
        public static string GridSettings_Grouping {
            get {
                return ResourceManager.GetString("GridSettings_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show header ähnelt.
        /// </summary>
        public static string GridSettings_ShowHeader {
            get {
                return ResourceManager.GetString("GridSettings_ShowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorting ähnelt.
        /// </summary>
        public static string GridSettings_Sorting {
            get {
                return ResourceManager.GetString("GridSettings_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format tip: you can use .NET format strings and {0} argument. ähnelt.
        /// </summary>
        public static string GridSettingsControl_ColumnsTip {
            get {
                return ResourceManager.GetString("GridSettingsControl_ColumnsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide UpToDate targets ähnelt.
        /// </summary>
        public static string HideUpToDateTargetsMenuItem {
            get {
                return ResourceManager.GetString("HideUpToDateTargetsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Invalid format&gt; ähnelt.
        /// </summary>
        public static string InvalidTimeStringFormat {
            get {
                return ResourceManager.GetString("InvalidTimeStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of MSBuild messages ähnelt.
        /// </summary>
        public static string MessagesIndicator_Description {
            get {
                return ResourceManager.GetString("MessagesIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages ähnelt.
        /// </summary>
        public static string MessagesIndicator_Header {
            get {
                return ResourceManager.GetString("MessagesIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disabled ähnelt.
        /// </summary>
        public static string NavigateToBuildFailureReasonCondition_Disabled {
            get {
                return ResourceManager.GetString("NavigateToBuildFailureReasonCondition_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On Build Failed ähnelt.
        /// </summary>
        public static string NavigateToBuildFailureReasonCondition_OnBuildDone {
            get {
                return ResourceManager.GetString("NavigateToBuildFailureReasonCondition_OnBuildDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On Error Raised ähnelt.
        /// </summary>
        public static string NavigateToBuildFailureReasonCondition_OnErrorRaised {
            get {
                return ResourceManager.GetString("NavigateToBuildFailureReasonCondition_OnErrorRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (none) ähnelt.
        /// </summary>
        public static string NoneMenuItem {
            get {
                return ResourceManager.GetString("NoneMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Settings... ähnelt.
        /// </summary>
        public static string OpenGeneralSettingsMenuItem {
            get {
                return ResourceManager.GetString("OpenGeneralSettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BuildVision ähnelt.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elapsed time ähnelt.
        /// </summary>
        public static string ProjectItemHeader_BuildElapsedTime {
            get {
                return ResourceManager.GetString("ProjectItemHeader_BuildElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build finish time  ähnelt.
        /// </summary>
        public static string ProjectItemHeader_BuildFinishTime {
            get {
                return ResourceManager.GetString("ProjectItemHeader_BuildFinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BuildOrder ähnelt.
        /// </summary>
        public static string ProjectItemHeader_BuildOrder {
            get {
                return ResourceManager.GetString("ProjectItemHeader_BuildOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build start time ähnelt.
        /// </summary>
        public static string ProjectItemHeader_BuildStartTime {
            get {
                return ResourceManager.GetString("ProjectItemHeader_BuildStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CommonType ähnelt.
        /// </summary>
        public static string ProjectItemHeader_CommonType {
            get {
                return ResourceManager.GetString("ProjectItemHeader_CommonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        public static string ProjectItemHeader_Configuration {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Errors ähnelt.
        /// </summary>
        public static string ProjectItemHeader_ErrorsCount {
            get {
                return ResourceManager.GetString("ProjectItemHeader_ErrorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extenders ähnelt.
        /// </summary>
        public static string ProjectItemHeader_ExtenderNames {
            get {
                return ResourceManager.GetString("ProjectItemHeader_ExtenderNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string ProjectItemHeader_FlavourType {
            get {
                return ResourceManager.GetString("ProjectItemHeader_FlavourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Framework ähnelt.
        /// </summary>
        public static string ProjectItemHeader_Framework {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FullName ähnelt.
        /// </summary>
        public static string ProjectItemHeader_FullName {
            get {
                return ResourceManager.GetString("ProjectItemHeader_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FullPath ähnelt.
        /// </summary>
        public static string ProjectItemHeader_FullPath {
            get {
                return ResourceManager.GetString("ProjectItemHeader_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string ProjectItemHeader_Language {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MainType ähnelt.
        /// </summary>
        public static string ProjectItemHeader_MainFlavourType {
            get {
                return ResourceManager.GetString("ProjectItemHeader_MainFlavourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages ähnelt.
        /// </summary>
        public static string ProjectItemHeader_MessagesCount {
            get {
                return ResourceManager.GetString("ProjectItemHeader_MessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ProjectItemHeader_Name {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        /// </summary>
        public static string ProjectItemHeader_OutputType {
            get {
                return ResourceManager.GetString("ProjectItemHeader_OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Platform ähnelt.
        /// </summary>
        public static string ProjectItemHeader_Platform {
            get {
                return ResourceManager.GetString("ProjectItemHeader_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Namespace ähnelt.
        /// </summary>
        public static string ProjectItemHeader_RootNamespace {
            get {
                return ResourceManager.GetString("ProjectItemHeader_RootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SolutionFolder ähnelt.
        /// </summary>
        public static string ProjectItemHeader_SolutionFolder {
            get {
                return ResourceManager.GetString("ProjectItemHeader_SolutionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State ähnelt.
        /// </summary>
        public static string ProjectItemHeader_State {
            get {
                return ResourceManager.GetString("ProjectItemHeader_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StateIcon ähnelt.
        /// </summary>
        public static string ProjectItemHeader_StateBitmap {
            get {
                return ResourceManager.GetString("ProjectItemHeader_StateBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UniqueName ähnelt.
        /// </summary>
        public static string ProjectItemHeader_UniqueName {
            get {
                return ResourceManager.GetString("ProjectItemHeader_UniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnings ähnelt.
        /// </summary>
        public static string ProjectItemHeader_WarningsCount {
            get {
                return ResourceManager.GetString("ProjectItemHeader_WarningsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu Item &quot;Build Output Files&quot; ähnelt.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_ExpanderHeader {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_ExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Built assemblies ähnelt.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_BuiltAssemblies {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_BuiltAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content files ähnelt.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_ContentFiles {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_ContentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Documentation ähnelt.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_Documentation {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Localized resources ähnelt.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_LocalizedRes {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_LocalizedRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Symbols ähnelt.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_Symbols {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML-serialization assemblies ähnelt.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_XmlSerAssemblies {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_Type_XmlSerAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy to the Clipboard ähnelt.
        /// </summary>
        public static string ProjectItemSettings_CopyBuildOutputFilesToClipboard_TypesLabel {
            get {
                return ResourceManager.GetString("ProjectItemSettings_CopyBuildOutputFilesToClipboard_TypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rebuild solution ähnelt.
        /// </summary>
        public static string RebuildSolutionButtonTooltip {
            get {
                return ResourceManager.GetString("RebuildSolutionButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report Issues ... ähnelt.
        /// </summary>
        public static string ReportIssues {
            get {
                return ResourceManager.GetString("ReportIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset after delay ähnelt.
        /// </summary>
        public static string ResetTaskBarItemInfoCondition_AfterDelay {
            get {
                return ResourceManager.GetString("ResetTaskBarItemInfoCondition_AfterDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset after mouse click ähnelt.
        /// </summary>
        public static string ResetTaskBarItemInfoCondition_ByMouseClick {
            get {
                return ResourceManager.GetString("ResetTaskBarItemInfoCondition_ByMouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string ResetTaskBarItemInfoCondition_Immediately {
            get {
                return ResourceManager.GetString("ResetTaskBarItemInfoCondition_Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not reset ähnelt.
        /// </summary>
        public static string ResetTaskBarItemInfoCondition_Never {
            get {
                return ResourceManager.GetString("ResetTaskBarItemInfoCondition_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy to the Clipboard ähnelt.
        /// </summary>
        public static string SelectedProjectItem_CopyBuildOutputFilesToClipboard_CopyMenuItem {
            get {
                return ResourceManager.GetString("SelectedProjectItem_CopyBuildOutputFilesToClipboard_CopyMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build Output Files ähnelt.
        /// </summary>
        public static string SelectedProjectItem_CopyBuildOutputFilesToClipboard_ParentMenuItem {
            get {
                return ResourceManager.GetString("SelectedProjectItem_CopyBuildOutputFilesToClipboard_ParentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Containing Folder ähnelt.
        /// </summary>
        public static string SelectedProjectItem_OpenContainingFolder_MenuItem {
            get {
                return ResourceManager.GetString("SelectedProjectItem_OpenContainingFolder_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Selected Project ähnelt.
        /// </summary>
        public static string SelectedProjectItemMenuItems {
            get {
                return ResourceManager.GetString("SelectedProjectItemMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Separator) ähnelt.
        /// </summary>
        public static string SeparatorIndicator_Header {
            get {
                return ResourceManager.GetString("SeparatorIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of succeeded projects ähnelt.
        /// </summary>
        public static string SuccessProjectsIndicator_Description {
            get {
                return ResourceManager.GetString("SuccessProjectsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Succeeded projects ähnelt.
        /// </summary>
        public static string SuccessProjectsIndicator_Header {
            get {
                return ResourceManager.GetString("SuccessProjectsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BuildVision ähnelt.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation is executed. Please wait... ähnelt.
        /// </summary>
        public static string UnknownBuildActionOrScope_BuildBeginText {
            get {
                return ResourceManager.GetString("UnknownBuildActionOrScope_BuildBeginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown exception ähnelt.
        /// </summary>
        public static string UnknownExceptionMsg {
            get {
                return ResourceManager.GetString("UnknownExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of projects which are up-to-date ähnelt.
        /// </summary>
        public static string UpToDateProjectsIndicator_Description {
            get {
                return ResourceManager.GetString("UpToDateProjectsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Up-to-date Projects ähnelt.
        /// </summary>
        public static string UpToDateProjectsIndicator_Header {
            get {
                return ResourceManager.GetString("UpToDateProjectsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of projects with warnings ähnelt.
        /// </summary>
        public static string WarningProjectsIndicator_Description {
            get {
                return ResourceManager.GetString("WarningProjectsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects with warnings ähnelt.
        /// </summary>
        public static string WarningProjectsIndicator_Header {
            get {
                return ResourceManager.GetString("WarningProjectsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of MSBuild warnings ähnelt.
        /// </summary>
        public static string WarningsIndicator_Description {
            get {
                return ResourceManager.GetString("WarningsIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnings ähnelt.
        /// </summary>
        public static string WarningsIndicator_Header {
            get {
                return ResourceManager.GetString("WarningsIndicator_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delay, ms ähnelt.
        /// </summary>
        public static string WindowSettings_DelayLabel {
            get {
                return ResourceManager.GetString("WindowSettings_DelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State on build begin ähnelt.
        /// </summary>
        public static string WindowSettings_WindowActionOnBuildBegin {
            get {
                return ResourceManager.GetString("WindowSettings_WindowActionOnBuildBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State on build error ähnelt.
        /// </summary>
        public static string WindowSettings_WindowActionOnBuildError {
            get {
                return ResourceManager.GetString("WindowSettings_WindowActionOnBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State on build success ähnelt.
        /// </summary>
        public static string WindowSettings_WindowActionOnBuildSuccess {
            get {
                return ResourceManager.GetString("WindowSettings_WindowActionOnBuildSuccess", resourceCulture);
            }
        }
    }
}
