namespace BuildVision.Contracts
{
    public enum ColumnsOrder
    {
        StateBitmap,
        BuildOrder,
        State,
        ErrorsCount,
        WarningsCount,
        MessagesCount,
        Name,
        Language,
        FlavourType,
        MainFlavourType,
        Configuration,
        Platform,
        BuildStartTime,
        BuildFinishTime,
        BuildElapsedTime,
        FullName,
        FullPath,
        UniqueName,
        Framework,
        CommonType,
        OutputType,
        //HabitatType,
        ExtenderNames,
        RootNamespace,
        SolutionFolder
    }
}